[package]
name = "jujutsu"
version = "0.7.0"
authors = ["Martin von Zweigbergk <martinvonz@google.com>"]
edition = "2021"
rust-version = "1.64"  # Remember to update CI, contributing.md, and flake.nix
license = "Apache-2.0"
description = "Jujutsu (an experimental VCS)"
homepage = "https://github.com/martinvonz/jj"
repository = "https://github.com/martinvonz/jj"
documentation = "https://docs.rs/jujutsu"
readme = "README.md"
keywords = ["VCS", "DVCS", "SCM", "Git", "Mercurial"]
categories = ["command-line-utilities", "development-tools"]
default-run = "jj"

[[bin]]
name = "jj"
path = "src/main.rs"

[[bin]]
name = "fake-editor"
path = "testing/fake-editor.rs"

[[bin]]
name = "fake-diff-editor"
path = "testing/fake-diff-editor.rs"

[[bench]]
name = "diff_bench"
harness = false

[workspace]
members = ["lib", "lib/testutils", "lib/gen-protos"]

[dependencies]
chrono = { version = "0.4.24", default-features = false, features = ["std", "clock"] }
clap = { version = "4.1.9", features = ["derive", "deprecated"] }
clap_complete = "4.1.5"
clap_mangen = "0.2.10"
config = { version = "0.13.3", default-features = false, features = ["toml"] }
crossterm = { version = "0.26", default-features = false }
dirs = "4.0.0"
git2 = "0.16.1"
esl01-renderdag = "0.3.0"
glob = "0.3.1"
hex = "0.4.3"
itertools = "0.10.5"
jujutsu-lib = { version = "=0.7.0", path = "lib", default-features = false }
maplit = "1.0.2"
once_cell = "1.17.1"
pest = "2.5.6"
pest_derive = "2.5"
regex = "1.7.2"
rpassword = "7.2.0"
serde = { version = "1.0", features = ["derive"] }
slab = "0.4.8"
strsim = "0.10.0"
tempfile = "3.4.0"
textwrap = "0.16.0"
timeago = { version = "0.4.1", default-features = false }
thiserror = "1.0.40"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", default-features = false, features = ["std", "ansi", "env-filter", "fmt"] }
indexmap = "1.9.2"
toml_edit = { version = "0.19.8", features = ["serde"] }

[target.'cfg(unix)'.dependencies]
libc = { version = "0.2.140" }

[dev-dependencies]
assert_cmd = "2.0.8"
assert_matches = "1.5.0"
criterion = "0.4.0"
criterion_bencher_compat = "0.4.0"
insta = { version = "1.28.0", features = ["filters"] }
predicates = "2.1.5"
regex = "1.7.2"
testutils = { path = "lib/testutils" }

[features]
default = ["jujutsu-lib/legacy-thrift"]
vendored-openssl = ["git2/vendored-openssl", "jujutsu-lib/vendored-openssl"]
