cargo-features = []

[workspace]
resolver = "2"
members = ["cli", "lib", "lib/testutils", "lib/gen-protos"]

[workspace.package]
version = "0.8.0"
license = "Apache-2.0"
rust-version = "1.71"                                 # NOTE: remember to update CI, contributing.md, changelog.md, and flake.nix
edition = "2021"
readme = "README.md"
homepage = "https://github.com/martinvonz/jj"
repository = "https://github.com/martinvonz/jj"
documentation = "https://github.com/martinvonz/jj"
categories = ["version-control", "development-tools"]
keywords = ["VCS", "DVCS", "SCM", "Git", "Mercurial"]

[workspace.dependencies]
anyhow = "1.0.75"
assert_cmd = "2.0.8"
assert_matches = "1.5.0"
backoff = "0.4.0"
blake2 = "0.10.6"
byteorder = "1.4.3"
bytes = "1.4.0"
cargo_metadata = "0.17.0"
clap = { version = "4.4.1", features = ["derive", "deprecated", "wrap_help"] }
clap_complete = "4.4.0"
clap_mangen = "0.2.10"
chrono = { version = "0.4.27", default-features = false, features = [
    "std",
    "clock",
] }
config = { version = "0.13.2", default-features = false, features = ["toml"] }
criterion = "0.5.1"
crossterm = { version = "0.26", default-features = false }
digest = "0.10.7"
dirs = "5.0.1"
either = "1.9.0"
esl01-renderdag = "0.3.0"
glob = "0.3.1"
git2 = "0.17.2"
hex = "0.4.3"
itertools = "0.11.0"
indexmap = "2.0.0"
libc = { version = "0.2.147" }
insta = { version = "1.31.0", features = ["filters"] }
maplit = "1.0.2"
num_cpus = "1.16.0"
once_cell = "1.18.0"
pest = "2.7.2"
pest_derive = "2.7.2"
pretty_assertions = "1.4.0"
prost = "0.11.9"
prost-build = "0.11.9"
rand = "0.8.5"
rand_chacha = "0.3.1"
rayon = "1.7.0"
regex = "1.9.4"
rpassword = "7.2.0"
rustix = { version = "0.38.10", features = ["fs"] }
smallvec = { version = "1.11.0", features = [
    "const_generics",
    "const_new",
    "union",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.105"
slab = "0.4.9"
strsim = "0.10.0"
tempfile = "3.8.0"
test-case = "3.1.0"
textwrap = "0.16.0"
thiserror = "1.0.47"
timeago = { version = "0.4.1", default-features = false }
toml_edit = { version = "0.19.14", features = ["serde"] }
tracing = "0.1.37"
tracing-chrome = "0.7.1"
tracing-subscriber = { version = "0.3.17", default-features = false, features = [
    "std",
    "ansi",
    "env-filter",
    "fmt",
] }
tokio = { version = "1.32.0" }
watchman_client = { version = "0.8.0" }
whoami = "1.4.1"
version_check = "0.9.4"
zstd = "0.12.4"

# put all inter-workspace libraries, i.e. those that use 'path = ...' here in
# their own (alphabetically sorted) block

jj-lib = { path = "lib" }
testutils = { path = "lib/testutils" }

[profile.release]
strip = "debuginfo"
codegen-units = 1
