[package]
name = "jujutsu"
version = "0.4.0"
authors = ["Martin von Zweigbergk <martinvonz@google.com>"]
edition = "2021"
rust-version = "1.60"  # Remember to update CI
license = "Apache-2.0"
description = "Jujutsu (an experimental VCS)"
homepage = "https://github.com/martinvonz/jj"
repository = "https://github.com/martinvonz/jj"
documentation = "https://docs.rs/jujutsu"
readme = "README.md"
keywords = ["VCS", "DVCS", "SCM", "Git", "Mercurial"]
categories = ["command-line-utilities", "development-tools"]
default-run = "jj"

[[bin]]
name = "jj"
path = "src/main.rs"

[[bin]]
name = "fake-editor"
path = "testing/fake-editor.rs"

[[bin]]
name = "fake-diff-editor"
path = "testing/fake-diff-editor.rs"

[[bench]]
name = "diff_bench"
harness = false

[workspace]
members = ["lib"]

[dependencies]
atty = "0.2.14"
chrono = { version = "0.4.22", default-features = false, features = ["std", "clock"] }
clap = { version = "4.0.9", features = ["derive", "deprecated"] }
clap_complete = "4.0.2"
clap_mangen = "0.2.2"
config = { version = "0.13.2", features = ["toml"] }
criterion = "0.4.0"
dirs = "4.0.0"
git2 = "0.15.0"
hex = "0.4.3"
itertools = "0.10.5"
jujutsu-lib = { version = "=0.4.0", path = "lib"}
maplit = "1.0.2"
pest = "2.4.0"
pest_derive = "2.4"
rand = "0.8.5"
regex = "1.6.0"
serde = { version = "1.0", features = ["derive"] }
tempfile = "3.3.0"
textwrap = "0.15.0"
thiserror = "1.0.37"

[dev-dependencies]
assert_cmd = "2.0.4"
criterion = "0.4.0"
criterion_bencher_compat = "0.4.0"
insta = "1.21.0"
lazy_static = "1.4.0"
regex = "1.6.0"
predicates = "2.1.1"
test-case = "2.2.2"

[features]
default = ["vendored-openssl"]
vendored-openssl = ["git2/vendored-openssl", "jujutsu-lib/vendored-openssl"]
