[package]
name = "jujutsu"
version = "0.6.1"
authors = ["Martin von Zweigbergk <martinvonz@google.com>"]
edition = "2021"
rust-version = "1.60"  # Remember to update CI
license = "Apache-2.0"
description = "Jujutsu (an experimental VCS)"
homepage = "https://github.com/martinvonz/jj"
repository = "https://github.com/martinvonz/jj"
documentation = "https://docs.rs/jujutsu"
readme = "README.md"
keywords = ["VCS", "DVCS", "SCM", "Git", "Mercurial"]
categories = ["command-line-utilities", "development-tools"]
default-run = "jj"

[[bin]]
name = "jj"
path = "src/main.rs"

[[bin]]
name = "fake-editor"
path = "testing/fake-editor.rs"

[[bin]]
name = "fake-diff-editor"
path = "testing/fake-diff-editor.rs"

[[bench]]
name = "diff_bench"
harness = false

[[bench]]
name = "trie"
harness = false

[workspace]
members = ["lib", "lib/testutils", "lib/gen-protos"]

[dependencies]
chrono = { version = "0.4.23", default-features = false, features = ["std", "clock"] }
clap = { version = "4.0.32", features = ["derive", "deprecated"] }
clap_complete = "4.0.7"
clap_mangen = "0.2.6"
config = { version = "0.13.3", default-features = false, features = ["toml"] }
crossterm = { version = "0.25", default-features = false }
dag = { git = "https://github.com/facebook/sapling", rev = "97e9d5112a4150286b44ba8544f543c69147e195", optional = true, default-features = false }
dirs = "4.0.0"
git2 = "0.16.0"
glob = "0.3.1"
hex = "0.4.3"
itertools = "0.10.5"
jujutsu-lib = { version = "=0.6.1", path = "lib", default-features = false }
maplit = "1.0.2"
once_cell = "1.17.0"
pest = "2.5.3"
pest_derive = "2.5"
regex = "1.7.1"
rpassword = "7.2.0"
serde = { version = "1.0", features = ["derive"] }
slab = "0.4.7"
tempfile = "3.3.0"
textwrap = "0.16.0"
timeago = { version = "0.4.0", default-features = false }
thiserror = "1.0.38"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", default-features = false, features = ["std", "ansi", "env-filter", "fmt"] }
indexmap = "1.9.2"

[target.'cfg(unix)'.dependencies]
libc = { version = "0.2.139" }

[dev-dependencies]
assert_cmd = "2.0.8"
criterion = "0.4.0"
criterion_bencher_compat = "0.4.0"
insta = { version = "1.26.0", features = ["filters"] }
predicates = "2.1.5"
regex = "1.7.1"
test-case = "2.2.2"
testutils = { path = "lib/testutils" }
uuid = "1.2.2"

[features]
sapling = ["dag"]
default = ["jujutsu-lib/legacy-thrift"]
vendored-openssl = ["git2/vendored-openssl", "jujutsu-lib/vendored-openssl"]
