site_name: Jujutsu docs
site_dir:  'rendered-docs'
# Not having this (or viewing the site locally, or from any place other than the
# site_url) leads to version switching failing to preserve the current path.
site_url: !ENV [SITE_URL_FOR_MKDOCS, 'https://martinvonz.github.io/jj/']
theme:
  name: 'material'
  language: 'en'
  features:
    # - navigation.top

  # Respect the users default settings and add a toggle for manually choosing 
  # automatic/light/dark palette.
  # taken from https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#system-preference
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

extra:
  version:
    provider: mike

# IMPORTANT: any changes to plugins have to be duplicated in
# `mkdocs-offline.yml`. See that file for more details.
plugins:
    - include-markdown # For the CLI reference
    - search
    - redirects:
        redirect_maps:

# Not all of these may be necessary, especially since the material
# theme substitutes for some of them
markdown_extensions:
  - toc:
      permalink: true
  - extra
  - sane_lists
  - admonition
  - codehilite:
      guess_lang: false
  # Allows list items with several paragraphs to be indented two spaces instead
  # of four (like GitHub markdown)
  - mdx_truly_sane_lists:
      # No, thanks, we'd like only somewhat sane lists :)
      # With `truly_sane: true`, together with breakless lists, it often splits
      # a single list in two.
      truly_sane: false
  # Fixes weird concatenation of list items that happens sometimes when
  # there is not a paragraph break between them and one of them has
  # multiple paragraphs.
  - mdx_breakless_lists
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# This lists all the files that become part of the documentation
nav:
- 'Home': 'index.md'

- 'Getting started':
      - 'Installation and Setup': 'install-and-setup.md'
      - 'Tutorial and Birds-Eye View': 'tutorial.md'
      - 'Working with GitHub': 'github.md'
      - 'Working on Windows': 'windows.md'

- FAQ: 'FAQ.md'

- "CLI Reference": 'cli-reference.md'

- Testimonials: 'testimonials.md'

- Concepts:
      - 'Working Copy': 'working-copy.md'
      - 'Branches': 'branches.md'
      - 'Conflicts': 'conflicts.md'
      - 'Operation Log': 'operation-log.md'
      - 'Glossary': 'glossary.md'

- 'Configuration':
      - 'Settings': 'config.md'
      - 'Revset language': 'revsets.md'
      - 'Templating language': 'templates.md'

- 'Comparisons':
      - 'Git comparison': 'git-comparison.md'
      - 'Git compatibility': 'git-compatibility.md'
      - 'Sapling': 'sapling-comparison.md'
      - 'Other related work': 'related-work.md'

- 'Technical details':
      - 'Architecture': 'technical/architecture.md'
      - 'Concurrency': 'technical/concurrency.md'
      - 'Conflicts': 'technical/conflicts.md'

- Contributing:
      - 'Guidelines and "How to...?"': 'contributing.md'
      - 'Code of conduct': 'code-of-conduct.md'

- 'Design docs': 
    - 'git-submodules': 'design/git-submodules.md'
    - 'git-submodule-storage': 'design/git-submodule-storage.md'
    - 'JJ run': 'design/run.md'
    - 'Sparse Patterns v2': 'design/sparse-v2.md'
    - 'Tracking branches': 'design/tracking-branches.md'


