[colors]
"error" = "red"
"warning" = "yellow"
"hint" = "cyan"

"conflict_description" = "yellow"
"conflict_description difficult" = "red"

"commit_id" = "blue"
"change_id" = "magenta"

# Unique prefixes and the rest for change & commit ids
"prefix" = { bold = true}
"rest" = "bright black"
"divergent rest" = "red"
"divergent prefix" = {fg = "red", underline=true}
"hidden prefix" = "default"
"divergent hidden" = {fg = "default", bold = true}
"divergent hidden prefix" = {fg = "default", underline = false}
"divergent hidden rest" = {fg ="bright black", bold = false}

"email" = "yellow"
"username" = "yellow"
"timestamp" = "cyan"
"working_copies" = "magenta"
"branch" = "magenta"
"branches" = "magenta"
"tags" = "magenta"
"git_refs" = "green"
"git_head" = "green"
"divergent" = "red"
"divergent change_id"="red"
"conflict" = "red"
"empty" = "green"
"separator" = "bright black"

"working_copy" = { bold = true }
"working_copy commit_id" = "bright blue"
"working_copy change_id" = "bright magenta"
# We do not use bright yellow because of how it looks on xterm's default theme.
# https://github.com/martinvonz/jj/issues/528
"working_copy email" = "yellow"
"working_copy timestamp" = "bright cyan"
"working_copy working_copies" = "bright magenta"
"working_copy branch"  = "bright magenta"
"working_copy branches" = "bright magenta"
"working_copy tags" = "bright magenta"
"working_copy git_refs" = "bright green"
"working_copy divergent" =  "bright red"
"working_copy divergent change_id" = "bright red"
"working_copy conflict" = "bright red"
"working_copy empty" = "bright green"
"diff header" = "yellow"
"diff empty" = "cyan"
"diff file_header" = { bold = true }
"diff hunk_header" = "cyan"
"diff removed" = "red"
"diff added" = "green"
"diff modified" = "cyan"
"op_log id" = "blue"
"op_log user" = "yellow"
"op_log time" = "cyan"
"op_log current_operation" = { bold = true }
"op_log current_operation id" = "bright blue"
"op_log current_operation user" = "yellow"  # No bright yellow, see comment above
"op_log current_operation time" = "bright cyan"
