# The code assumes that this table exists, so don't delete it even if you remove
# all aliases from here.
[aliases]
amend = ["squash"]
b = ["bookmark"]
ci = ["commit"]
unamend = ["unsquash"]

[diff.color-words]
max-inline-alternation = 3
context = 3

[diff.git]
context = 3

[ui]
# TODO: delete ui.allow-filesets in jj 0.26+
allow-filesets = true
always-allow-large-revsets = false
diff-instructions = true
graph.style = "curved"
paginate = "auto"
pager = { command = ["less", "-FRX"], env = { LESSCHARSET = "utf-8" } }
log-word-wrap = false
log-synthetic-elided-nodes = true
conflict-marker-style = "diff"

[ui.movement]
edit = false

[snapshot]
max-new-file-size = "1MiB"
auto-track = "all()"
auto-update-stale = false
