# The code assumes that this table exists, so don't delete it even if you remove
# all aliases from here.
[aliases]
amend = ["squash"]
co = ["checkout"]
unamend = ["unsquash"]

[ui]
# TODO: delete ui.allow-filesets in jj 0.26+
allow-filesets = true
always-allow-large-revsets = false
diff-instructions = true
paginate = "auto"
pager = { command = ["less", "-FRX"], env = { LESSCHARSET = "utf-8" } }
log-word-wrap = false
log-synthetic-elided-nodes = true

[ui.movement]
edit = false

[snapshot]
max-new-file-size = "1MiB"
