# NOTE: ensure you update docs/revsets.md with documentation when
# adding/updating any of these aliases

[revsets]
fix = "@"
log = "@ | ancestors(immutable_heads().., 2) | trunk()"

[revset-aliases]
'trunk()' = '''
latest(
  remote_branches(exact:"main", exact:"origin") | 
  remote_branches(exact:"master", exact:"origin") | 
  remote_branches(exact:"trunk", exact:"origin") |
  remote_branches(exact:"main", exact:"upstream") |
  remote_branches(exact:"master", exact:"upstream") |
  remote_branches(exact:"trunk", exact:"upstream") |
  root()
)
'''

'immutable_heads()' = 'trunk() | tags()'
'immutable()' = '::(immutable_heads() | root())'
'mutable()' = '~immutable()'
