cfgs = ["boringssl"]
features = ["unstable_boringssl"]
extra_deps = [
    "third-party//bssl:crypto",
    "third-party//bssl:ssl",
    "third-party//bssl/rust:bssl-sys",
]
omit_deps = ["bssl-sys"]

buildscript = []
